sudo: false
language: node_js
before_install:
  - curl --location http://git.io/1OcIZA | bash -s
node_js:
  - '0.8'
  - '0.10'
  - node
  - iojs
branches:
  only:
    - master
notifications:
  email:
    - rod@vagg.org
script: npm test
